# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1381394814);
user_pref("app.update.lastUpdateTime.background-update-timer", 1381394672);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1381394432);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1381394552);
user_pref("app.update.migrated.updateDir", true);
user_pref("app.update.mode", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.link.open_newwindow", 2);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.search.update", false);
user_pref("browser.sessionstore.restore_on_demand", false);
user_pref("browser.slowStartup.averageTime", 3046);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20130910160258");
user_pref("browser.startup.homepage_override.mstone", "24.0");
user_pref("browser.startup.page", 0);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("browser.urlbar.autocomplete.enabled", false);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1381480831689");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1381394431689");
user_pref("datareporting.sessions.current.activeTicks", 3);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1324);
user_pref("datareporting.sessions.current.main", 145);
user_pref("datareporting.sessions.current.sessionRestored", 1360);
user_pref("datareporting.sessions.current.startTime", "1381395029653");
user_pref("datareporting.sessions.current.totalTime", 13);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1381394430329,\"a\":40,\"t\":262,\"c\":true,\"m\":200,\"fp\":4383,\"sr\":5496}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1381394693739,\"a\":35,\"t\":202,\"c\":true,\"m\":1,\"fp\":1741,\"sr\":1802}");
user_pref("dom.disable_open_during_load", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:24.0");
user_pref("extensions.hotfix.certs.1.sha1Fingerprint", "91:53:98:0C:C1:86:DF:47:8F:35:22:9E:11:C9:A7:31:04:49:A1:AA");
user_pref("extensions.hotfix.lastVersion", "20130826.01");
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"otis@digitalpersona.com\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\DigitalPersona\\\\Bin\\\\FirefoxExt\",\"mtime\":1351443908556,\"rdfTime\":1259667464000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1379564433059,\"rdfTime\":1379564433013}}},{\"name\":\"winreg-app-user\",\"addons\":{\"otis@digitalpersona.com\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\DigitalPersona\\\\Bin\\\\firefoxext\",\"mtime\":1351443908556,\"rdfTime\":1259667464000}}}]");
user_pref("extensions.lastAppVersion", "24.0");
user_pref("extensions.lastPlatformVersion", "24.0");
user_pref("extensions.newAddons", false);
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.update.notifyUser", false);
user_pref("gecko.buildID", "20130910160258");
user_pref("gecko.mstone", "24.0");
user_pref("general.autoScroll", false);
user_pref("gfx.direct3d.last_used_feature_level_idx", 1);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("toolkit.startup.last_success", 1381395029);
user_pref("toolkit.telemetry.previousBuildID", "20130910160258");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1383986438);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
user_pref("xpinstall.whitelist.required", false);
